name: Fix terraform file formatting

on: workflow_dispatch

jobs:
  format:
    runs-on: ubuntu-latest
    name: Check terraform file are formatted correctly
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
        with:
          path: terraform/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: "chore: terraform fmt"
          title: Reformat terraform files
          body: Update terraform files to canonical format using `terraform fmt`
          branch: automated-terraform-fmt
